### ISSUE TITLE
Make a GUI for this script. 

### ISSUE THREAD

**Issue by utkarshbajaj** [utkarshbajaj/Find-IMDB-Ratings#4]
Make a GUI for this script using PySimpleGUI or anything of your choice, update the readme accordingly. 
Look here for reference: https://opensource.com/article/18/8/pysimplegui

**Comment by Aravindha1234u** [comment]
@utkarshbajaj Can you assign this to me I would love to work.

**Comment by utkarshbajaj** [comment]
> @utkarshbajaj Can you assign this to me I would love to work.

Sure!

**Comment by Aravindha1234u** [comment]
I have done with the GUI do you have any requirements.
I have made few changes too.

1. Instead of get directory and find the film name from files in directory. I taught of adding single file with films name.
![image](https://user-images.githubusercontent.com/52521300/94840331-e2378800-0435-11eb-99a0-6629239e4bac.png)

2. Instead of saving to csv file, I taught to display in table to make it easier 
![image](https://user-images.githubusercontent.com/52521300/94840411-03987400-0436-11eb-9d52-bc76fb2f649b.png)

There is issue in scraping the Genres which should be worked on.

**Comment by utkarshbajaj** [comment]
Hey! Please take the input as the directory path only, you can browse also using finder I guess (idk if you have done that)
Just that the input should be a folder and we should get the directory path in the code. 
Genres is working fine, please pull the latest changes and try again 
And please save in a csv too, alongside you can display as well.

**Comment by Aravindha1234u** [comment]
I guess that's Done.
![image](https://user-images.githubusercontent.com/52521300/94877633-b984b200-0478-11eb-9cc4-1d17c7a20f6b.png)
![image](https://user-images.githubusercontent.com/52521300/94878033-dbcaff80-0479-11eb-8f32-eede65c17959.png)
